### PR TITLE
correspond to file URI scheme

### PR DESCRIPTION
**Pull request by kuniiskywalker**
I want to be able to load facebook sdk loading with https even if it accessed by file URI scheme.

example, file://exmaple.com/index.html

### CODE REVIEW

**Comment by kennetpostigo** [comment]
Interesting, @dashracer can you verify that this doesn't break the example app from the repo? The way to test this out is to switch the `import ... from 'react-facebook-login-component'` to the `/dist/react-facebook-login-component.js` file.

**Comment by kuniiskywalker** [comment]
I made a mistake, the example is here.

file:///Users/kunii/git/www/index.html

**Comment by kennetpostigo** [comment]
@kuniiskywalker I will review this, on the weekend.

**Comment by kuniiskywalker** [comment]
@kennetpostigo  Thank you!

**Comment by kuniiskywalker** [comment]
Sorry, because file URI can not specify a callback URL, I done this issue.
I wrapped this component and succeeded in authentication using InAppBrowswer on a native application running on JS.
Thank you for a wonderful idea!

https://github.com/kuniiskywalker/hybrid-react-facebook-login-component

**Pull request closed without merging**
