### PR TITLE
Allow for more flexible customization of login button

### PR DESCRIPTION
**Pull request by koss-lebedev**
Hey @kennetpostigo ,

I think this update should make it easier for people to customize properties of login button other than `className`. For example, it's very common to disable the button while login is in progress and right now there's no way to do that. With this update, we can set any attributes and they will be passed down to the button element.

### CODE REVIEW

**Comment by kennetpostigo** [comment]
Hey @koss-lebedev ! Thanks for the PR :) Did you verify it working on the example project in the repo?

**Comment by koss-lebedev** [comment]
Yesterday I tested it in my own project, but now I also verified it with the example project in the repo :) I also added a tiny update to it to be able to see that the properties are applied correctly.

One thing I forgot to mention is that this update changes `class` property to a more common name in React projects `className`. What do you think about that?

Thanks!

**Comment by kennetpostigo** [comment]
@koss-lebedev sounds good! Thanks so much for contributing :) Would it be okay for me to review all the changes and make a release on Friday to npm?

**Comment by koss-lebedev** [comment]
@kennetpostigo Yes, definitely! I look forward to a new release

Cheers!

**Comment by kennetpostigo** [comment]
New version `0.8.0` published :) @koss-lebedev  Do you think you can make the same PR here: https://github.com/kennetpostigo/react-google-login-component/

**Comment by koss-lebedev** [comment]
@kennetpostigo  Awesome! Yes, I'll create a PR for it tomorrow, I was planning to check google authentication anyway :)

**Pull request merged**
